### ISSUE TITLE
Open VSX repo has old version

### ISSUE THREAD

**Issue by m1ga** [tidev/vscode-titanium#1029]
The open vsx repo https://open-vsx.org/extension/Axway/vscode-titanium
still uses the old Axway 0.14.0 version! Could this be updated? It has almost 500 downloads and people who use VSCodium will search there by default

**Comment by ewanharris** [comment]
Shoot yeah I forgot to get that removed, will get that done.

**Comment by ewanharris** [comment]
Removed the Axway extension and publish the [TiDev one](https://open-vsx.org/extension/TiDev/titanium-sdk). Currently waiting for my namespace claim to go through so that warning will be removed.

Once done I'll make sure some other folks have access and also setup open-vsx publishing in actions

**Comment by m1ga** [comment]
awesome. Thanks for the quick update :+1: I'll close this one since its available now

**Comment by ewanharris** [comment]
The one and only @cb1kenobi configured my open-vsx token in actions so next time we publish this it should do both open-vsx and vscode marketplaces at the same time
