### ISSUE TITLE
Adding build options for macos, macos-adhoc, MacAppStore

### ISSUE THREAD

**Issue by mbender74** [tidev/vscode-titanium#1129]
adding missing option to build for macos, macos-adhoc and MacAppStore

**Comment by ewanharris** [comment]
Hey @mbender74, I just put up a PR that starts to add this over at #1130 it builds but I haven't tested much further than that.

If you wanted to give it a spin you can grab the vsix from the artifacts [here](https://github.com/tidev/vscode-titanium/actions/runs/4824477978) and install as described [here](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix)

**Comment by mbender74** [comment]
@ewanharris works great! that was quick! 👍
