### ISSUE TITLE
 Autocomplete feature not working 

### ISSUE THREAD

**Issue by blackjyn** [tidev/vscode-titanium#1165]
This is my env:
- Titanium CLI v6.1.1, 
- Titanium SDK v12.1.2.GA
- Alloy v2.0.2
- Titanium ext v1.1.0
- Windows x64 

In addition , I disable other ext that may promotes conflict like XML by redhat and other plugins that rely on TypeScript.
However autocompletion didn't work at all either for *.js files and the Titanium's *.xml file.

Android build and live view are just running perfectly, other ext functionalities like creating project are just fine.
Only Autocompletion that is not working.

Help?

**Comment by ewanharris** [comment]
Hey @blackjyn unfortunately the debugging/troubleshooting for this isn't easy sorry :/ I can try and add some logging that might provide some insight on it, but I'll try and add some things to check:

* Is the Titanium project the only folder you have open or do you have multiple? If multiple, is the Titanium project the first folder?
* Is there a `completions-v3.json` file that corresponds to your Alloy/SDK version at `~/.titanium/completions/alloy` and `~/.titanium/completions/titanium`
* The files you're using match the regex [like this](https://github.com/tidev/vscode-titanium/blob/master/src/providers/index.ts#L23-L25)

**Comment by blackjyn** [comment]
Hi @ewanharris , thank you.
I only open Titanium project and not opening any other project. 

Sorry , I can't find ` completions-v3.json` , I don't have `.titanium` folder inside my project.

I've tried both creating project via CLI and VSCode, none of them including `.titanium` folder

**Comment by ewanharris** [comment]
The `.titanium` folder lives in your user directory not a project folder. So if you run `ls ~/.titanium/completions/titanium` then it should list some SDK versions that completions were generated for.

It's weird that everything else is working but completions, I would assume that an issue with the providers would break the functionality of the entire extension as a whole.

Let me review where we can possibly improve the logging and see if I can provide a debug build to test

**Comment by blackjyn** [comment]
My bad. 

unfortunately the `completions-v3.json` is not there, I got only 2 files: 


![titanium](https://github.com/tidev/vscode-titanium/assets/6046191/38971c28-6db4-40cb-a979-e3ddd42b9d6e)

**Comment by ewanharris** [comment]
There must be an error when generating the completions file I guess then, are you getting a notification in VS Code with a message like `Error generating autocomplete suggestion`

**Comment by blackjyn** [comment]
I open the extension logs, and get this:
`TiDev.titaniumsdk provider FAILED`

![tiedv provider failed](https://github.com/tidev/vscode-titanium/assets/6046191/a8e404b3-10f6-41f7-a19f-447f86f839a0)

**Comment by blackjyn** [comment]
For workarounds , I downloaded and installed [https://pulsar-edit.dev/download.html](Pulsar) and install the Tidev Plugin.
After doing setup , Tidev for Pulsar recognized SDKs and creating the `completions-v3.json`.
And yeah, since the `completions-v3.json` existed it works on VScode too. 
![tidevPulsar-autocompletionsworks](https://github.com/tidev/vscode-titanium/assets/6046191/bade5c1c-aeb8-4290-bee7-cb99e43e4b17)

So, the problem is clearly on the  titatnium's VSCode ext

**Comment by ewanharris** [comment]
Thank you for digging into that, the file should be created at startup in VS Code as it is in the Pulsar extension. What's extra weird is that both use the same package (and same version of that package) to create the file so I'm not too sure what might be up. I'll take a look into whether this is down to the recent changes in VS Code to improve security maybe

**Comment by ewanharris** [comment]
Once I walked through the code it became obvious what the issue was here, I've a fix up in #1171
