### ISSUE TITLE
Add a default `.vscode` directory setup on project creation

### ISSUE THREAD

**Issue by ewanharris** [tidev/vscode-titanium#158]
When creating a new project the extension should create a `.vscode` directory with the following:

* `settings.json` to tell vscode to ignore certain folders, such as `build/` (always), `Resources/` (alloy only), `platform/` (alloy only)
* `launch.json` with a basic debugger setup

credit to @jquick-axway for this idea (thanks!)

**Comment by jquick-axway** [comment]
For a Classic app, my `.vscode/settings.json` looks like this...
```json
{
	"files.exclude": {
		"build/": true
	},
	"search.exclude": {
		"build/": true
	},
	"files.watcherExclude": {
		"build/": true
	},
}
```

For Alloy, my `.vscode/settings.json` looks like the below. I've tested with "kitchensink-v2" and it correctly hides the root "i18n", "platform", and "Resources" folders... but still reveals the same folders under the "app" subdirectory.
```json
{
	"files.exclude": {
		"build/": true,
		"i18n/": true,
		"platform/": true,
		"Resources/": true
	},
	"search.exclude": {
		"build/": true,
		"i18n/": true,
		"platform/": true,
		"Resources/": true
	},
	"files.watcherExclude": {
		"build/": true,
		"i18n/": true,
		"platform/": true,
		"Resources/": true
	},
}
```

Not sure if there is a better way of doing the above without the duplication. I'll leave it to the experts. :)

**Comment by ewanharris** [comment]
This is now done in `ti create` so closing
