### ISSUE TITLE
Unable to launch on device via extension and unable to create a launch.json

### ISSUE THREAD

**Issue by DzzD** [tidev/vscode-titanium#993]
Hi, 

I try to launch on my device from titanium extension panel but it always start on the emulator regardless of the button I click, both have the same effect, it start on the emulator : 
![image](https://user-images.githubusercontent.com/12198339/164912796-a451d5b2-f9b9-4ae8-a61d-c4dcfd8bdfcd.png)

Also I am enalbe to create a new lauch.json configuration as it throw an error : 
![image](https://user-images.githubusercontent.com/12198339/164912782-a5a251fb-0cee-4c88-9378-bbca475e81d1.png)

Titanium configuration looks ok : 
![image](https://user-images.githubusercontent.com/12198339/164912831-aaa982a3-cb39-4a6b-910f-2bf427307c21.png)

**Comment by DzzD** [comment]
I have to give some more information, I am talking about a "module" project, it works on "application" project.

So the problem is only that for a "module" project the command line launched is not the same as for an application, because the device is not specified and then it always start on emulator

**Comment by ewanharris** [comment]
Module project support is kind of half baked to be honest. Some of the features need to be restricted to those only supported by the CLI (i.e. no device/specific target builds as that's what's supported in the CLI) and no support for debugging a project.

The fixes here are most likely to not show devices or specific emulators for module projects, then maybe work in tandem to improve the CLI/SDK side to allow this to be exposed (but that's a much bigger task imo).

**Comment by DzzD** [comment]
Ok, I understand, so you are right, as a first correction hidding devices & emulator would be a good choice, then it wont look anymore as a bug.

I got another question, is that possible to add a pre/post build/package script in vscode ? 

What I am looking for is to improve my module development workflow and make it less tedious, so I would like to be able to pre-build the module when I build & deploy any other application that use it. I know how to do it by script (bat/sh) as it is pretty simple, but is that possible to add something in vscode to do it ? like in a launch.json ? or other ?

**Comment by ewanharris** [comment]
You might want to look at creating a [compound task](https://code.visualstudio.com/docs/editor/tasks#_compound-tasks), they're briefly mentioned in the [docs in this repo](https://github.com/tidev/vscode-titanium/blob/master/doc/tasks.md#orchestrating-tasks). So you'd be creating a task to build, a task to unzip, and then a compound task that runs the two in sequence. You could then also add a `titanium-build` task for the app if you wanted to go the whole way.

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "titanium-package",
			"label": "iOS Module Build",
			"titaniumBuild": {
				"platform": "ios",
				"projectType": "module"
			}
		},
		{
			"type": "shell",
			"label": "Extract Module",
			"command": "unzip ${workspaceFolder}/ios/dist/*.zip -d ~/Documents/Workspace/testing/"
		},
		{
			"label": "Build and Extract",
			"dependsOrder": "sequence",
			"dependsOn": ["iOS Module Build", "Extract Module"]
		}
	]
}

```

It might be useful for the extension to offer the same outputs that Studio used to when packaging a module. Alongside the directory to place the zip into, it would offer to install the module globally or in an app for you. Do you think that would be useful? (pretty much just performing the `Extract Module` task above for you)

**Comment by ewanharris** [comment]
@DzzD I have a PR open for a change to improve this at #998. When a module project is selected (i.e. the first Titanium project in the workspace) the explorer will now only show Build and Package options. If you wanted to give it a try you can download the built vsix from [the run artifacts](https://github.com/tidev/vscode-titanium/actions/runs/2278336986) and install it using `code --install-extension <path-to-vsix>`

**Comment by DzzD** [comment]
> Module project support is kind of half baked to be honest. Some of the features need to be restricted to those only supported by the CLI (i.e. no device/specific target builds as that's what's supported in the CLI) and no support for debugging a project.
> 
> The fixes here are most likely to not show devices or specific emulators for module projects, then maybe work in tandem to improve the CLI/SDK side to allow this to be exposed (but that's a much bigger task imo).

After looking a bit more on the build process of module, it does not seems so much complicated (but I may be wrong).

I saw two problems : 
1 - The vscode extension does not provide the target & device ID arguments (--target device|emulator  --device-id id)
2 - The tianium_mobile source code does not take care of thoses paramameters : 
https://github.com/tidev/titanium_mobile/blob/master/android/cli/commands/_buildModule.js#L891

I would happily like to help and try to correct this, but I am a bit lost on how to test my modification/use my own Titanium mobile build locally ?

**Comment by DzzD** [comment]
I just finished the modification :

https://github.com/tidev/vscode-titanium/pull/999

**Comment by DzzD** [comment]
In the meantime how can I use this WIP extension in replacment of the official release I use ? 

I mean can I built it and install it in replacement of the official VSCodeTitanium extension ?

(Never worked on VSCode extension before so I did not really know a lot about it)

**Comment by ewanharris** [comment]
Once the CI has ran you can download a built vsix that you can install in VS Code. In the artifacts for your [CI run](https://github.com/tidev/vscode-titanium/actions/runs/2289770402) you can download that and do `code --install-extension <path-to-vsix>`. If you make changes you can also package it locally using `npx vsce package` in your vscode-titanium directory and install that the same way

**Comment by DzzD** [comment]
> Once the CI has ran you can download a built vsix that you can install in VS Code. In the artifacts for your [CI run](https://github.com/tidev/vscode-titanium/actions/runs/2289770402) you can download that and do `code --install-extension <path-to-vsix>`. If you make changes you can also package it locally using `npx vsce package` in your vscode-titanium directory and install that the same way

And that's work perfecly ! thanks
